version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: codedeploy/app_stop.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 300
      runas: ubuntu